### ISSUE TITLE
 AuditLogCollector.py - AttributeError: 'collections.deque' object has no attribute 'insert'

### ISSUE THREAD

**Issue by funk0id** [ddbnl/office365-audit-log-collector#12]
So close to getting this running but am hitting the following issue when starting the  AuditLogCollector.py script. 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "AuditLogCollector.py", line 119, in monitor_blobs_to_collect
    self._graylog_interface.stop()
  File "/var/opt/office365-audit-log-collector/GraylogInterface.py", line 24, in stop
    self.queue.insert(0 if not gracefully else -1, 'stop monitor thread')
AttributeError: 'collections.deque' object has no attribute 'insert'

**Comment by ddbnl** [comment]
Fixed in c3b0c99.
