### ISSUE TITLE
Could not connect to Graylog interface

### ISSUE THREAD

**Issue by ajabir** [ddbnl/office365-audit-log-collector#74]
I am running latest version on Linux since early June 2024, and it has been working fine.  However, since last week I noticed that there are problems with the program.  When I run the program manually, it throws error after some time:

Could not connect to Graylog interface on: 10.xx.yy.48:5010 with: Cannot assign requested address (os error 99)

With RUST_BACKTRACE=1 gives:

thread 'main' panicked at src/interfaces/graylog_interface.rs:43:17:
Could not connect to Graylog interface on: 10.xx.yy.48:5010 with: Cannot assign requested address (os error 99)
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: office_audit_log_collector::interfaces::graylog_interface::GraylogInterface::get_socket
   3: <office_audit_log_collector::interfaces::graylog_interface::GraylogInterface as office_audit_log_collector::interfaces::interface::Interface>::send_logs::{{closure}}
   4: office_audit_log_collector::collector::Collector::output::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::runtime::Runtime::block_on
   7: office_audit_log_collector::main

Is there anything needs to be tuned in kernel settings?

Thanks!

**Comment by chrisalibby** [comment]
I had a similar issue when connecting from another server.  I moved the script to the Graylog server so I could connect via 127.0.0.1 to correct the issue.
```
thread 'main' panicked at src/interfaces/graylog_interface.rs:43:17:
Could not connect to Graylog interface on: x.x.x.x:5010 with: Cannot assign requested address (os error 99)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
